### PR TITLE
Read Ref IDs as uint64

### PR DESCRIPTION
**Pull request by sivachandran**
Fixes overflow error in parsing Ref IDs

### CODE REVIEW

**Review by korniltsev — APPROVED** [review]

**Comment by sivachandran** [comment]
Can you tag a release? I need the fix in my usage.

**Comment by korniltsev** [comment]
May I ask why can't you go get jfr-parser@a8d22a1 ?

**Comment by korniltsev** [comment]
or it doe snot work?

**Comment by sivachandran** [comment]
it works only if i do
```
go get github.com/grafana/jfr-parser@a8d22a1
go get github.com/grafana/jfr-parser/pprof@a8d22a1
```
in this case there is no change under `pprof`. otherwise without the second go get i won't get changes under `pprof`.

is there a reason to have nested package?

**Comment by korniltsev** [comment]
> is there a reason to have nested package?

The first one is for parsing, and the other is for pprof producing. They have slightly different dependencies. Furthermore the latter one has a little bit of  pyroscope specifics.

**Comment by sivachandran** [comment]
> The first one is for parsing, and the other is for pprof producing. They have slightly different dependencies. Furthermore the latter one has a little bit of pyroscope specifics.
I understand.

But considering the fact pprof depends on `jfr-parser/parser` and can't be used independently why don't we keep everything under single package. It would make the dependency management and releasing simpler.

**Comment by korniltsev** [comment]
Cause there may be users who dont need pprof

**Comment by sivachandran** [comment]
Hmm... make sense. Thanks for explaining!

**Pull request merged**
