### PR TITLE
Add support for ObjectAllocationSample event

### PR DESCRIPTION
**Pull request by sivachandran**
The PR adds support for `ObjectAllocationSample` JFR event.

The event was introduced in JDK 16. Unlike the events `ObjectAllocationInNewTLAB` and `ObjectAllocationOutsideTLAB` the `ObjectAllocationSample` is a sampling event and adds less overhead compared with the TLAB based events. But the allocation metric provided by `ObjectAllocationSample` event is less accurate due to its sampling nature.

The TLAB based events are disabled by default in JDK 16+ and only `ObjectAllocationSample` event is enabled by default. Please refer the following links for more details

https://bugs.openjdk.org/browse/JDK-8262902
https://bugs.openjdk.org/browse/JDK-8257602

NOTE: The jfr to pprof formatter has been modified to include the profile index in the filename as now there can be three memory profiles. We don't want them each overwrite each other (it was overwriting even in TLAB based events).

### CODE REVIEW

**Review by korniltsev — APPROVED** [review]

**Comment by sivachandran** [comment]
@korniltsev can you tag the changes?

**Comment by korniltsev** [comment]
Is this the last PR from you or more coming ? :)

**Comment by sivachandran** [comment]
I don't know :smile: 

I'm investigating empty profiles from OpenJDK 21 JFR. But it is not just jfr-parser, even async-profiler produces empty pprof. But it looks like I need to take it up with the profiler author which would take time. So I don't foresee any PRs tomorrow(hopefully).

It would help me if you can tag as I don't have to use my fork and git mod replace. But it is fine if you want to wait.

**Comment by korniltsev** [comment]
I will tag in an hour

**Pull request merged**
